### ISSUE TITLE
Consider ditching ProtonMail or put a note

### ISSUE THREAD

**Issue by heygambo** [pluja/awesome-privacy#133]
Apparently, ProtonMail shares IP addresses with the police even if there is no major crime involved.

https://twitter.com/tenacioustek/status/1434604102676271106

**Comment by ph00lt0** [comment]
> Apparently, ProtonMail shares IP addresses with the police even if there is no major crime involved.
> 
> https://twitter.com/tenacioustek/status/1434604102676271106

First of all, you can disable logging or wipe the logs. Secondly I do not think they have a choice. Besides that if you are hiding from law enforcement it generally is a bad idea to use your own IP address.

**Comment by pluja** [comment]
I am considering what should I do with Protonmail.

**Comment by jonatasbaldin** [comment]
It's tricky because they advertised never logging any IPs, but did anyway when the gov demanded. 

In this case, I don't think _any_ email provider would have choice to go against the law and court.

More, they written a pretty good [article](https://protonmail.com/blog/climate-activist-arrest/) on what happened and gave alternatives: use a VPN (they have their own) or use Tor (and they provide an onion site too).

I think we can add a note on the entry with their article link, but keep them on the list. They are still one of the best email services regarding privacy out there.

**Comment by heygambo** [comment]
@jonatasbaldin Thanks for the article. They seem to have addressed the issue well.
Should we close this?

**Comment by pluja** [comment]
I will link the article and keep ProtonMail listed. Closing.
