### ISSUE TITLE
Remove [ente.io]/[Photo Storage]

### ISSUE THREAD

**Issue by DudeDude2** [pluja/awesome-privacy#197]
I'm sorry if this is the wrong way to do it but here goes:

I was looking for photo storage alternatives and looked into ente.io and found this comment that might warrant the removal of said service from this list:

https://www.reddit.com/r/PrivacyGuides/comments/rjzc9s/compare_cryptee_and_enteio/

Look at the top comment from the user "aliceturing"

**Comment by pluja** [comment]
Just for the record, a copy&paste of the comment:

89
[u/aliceturing](https://libreddit.kavin.rocks/user/aliceturing) [Dec 19 '21](https://libreddit.kavin.rocks/r/PrivacyGuides/comments/rjzc9s/compare_cryptee_and_enteio/hp7gu68/?context=3) Dec 19 '21

Where do I even begin.

First off anyone who has ever read any legal document would easily be able to see that folks over at Ente clearly haven’t done any legal homework, and I wouldn’t ever recommend anyone serious about their privacy to consider using Ente. Your message got me all curious, so I just read through their terms and privacy policy.

1 – Ente claims to be open source, and have a GPL-3 license on their github, yet, their terms and conditions have an IP clause that’s clearly conflicting with GPL-3 like this :

    You are not allowed to, and you can't let anyone else use, copy, alter, distribute, display, licence, modify or reproduce, reverse assemble, reverse compile, communicate, share, transmit or otherwise make available, (whether digitally, electronically, by linking, or in hard copy or by any means whatsoever), any of our code, content, copyright materials, intellectual property or other rights without getting our permission in writing, other than in order to use our services as intended or as allowed under any open source licences under which we use intellectual property provided by others.

What this tells me is that they clearly don’t have an attorney, nor did they care or bother enough to hire a lawyer to read through what they copy pasted onto their terms and conditions / privacy policy etc.

2 – Why does this matter? Ente is a company(?) based in India. A country so famously bad for privacy protections that even Facebook / Whatsapp decided to sue the government.

https://www.forbes.com/sites/aayushipratap/2021/06/15/whatsapps-fight-with-the-indian-government-over-its-data-privacy-rules-may-have-global-reverberations/

So I don’t think you should trust Ente with anything. They’re based in a privacy hot-zone, and clearly haven’t done any legal homework before attempting to make an app about privacy.

Let’s build a bit more upon this though before we write them off for being based in India alone shall we?

3 – They have a copyright infringement / takedown clause in their terms and conditions. Like wtf. If they can’t see what you upload, and if it’s actually end-to-end encrypted as they claim, they wouldn’t need a copyright clause like this :

    We respect the copyright of others and require that users of our services comply with copyright laws. You are strictly prohibited from using our services to infringe copyright. You may not upload, download, store, share, access, display, stream, distribute, e-mail, link to, communicate, transmit, or otherwise make available any files, data, or content that infringes any copyright or other proprietary rights of any person or entity.

Why is this weird? Because they wouldn’t be able to prove copyright infringements without being able to check the content, thus wouldn’t be able to take down anything. If they have this clause, and could take down content, I’ve got multiple burning questions.

Either a lawyer wrote this, and they can see your files and can confirm copyright infringements, and can take down your content.

Or they don’t have a lawyer, nobody read through this, and they just copy pasted terms and privacy policies, and that’s an even bigger red flag given that they’re based in a country with horrifying privacy and online-scam legal track record.

You can probably see where I’m going with this… but I’ll still elaborate bit more because why not.

4 – Let’s look at their strange Copyright Counter-Notices section.

    We process all takedown notices based on good faith acceptance of the representations from the party submitting the takedown notice. We do not review the material before processing the takedown notice.

​

So wait. I can submit a copyright take-down notice for all user accounts on Ente right now, and have all users’ photos taken down?

​

    You may file a counter-notice if you believe that access to a file you have uploaded has been wrongly disabled because it was the subject of an incorrect takedown notice. You should only do so if you are confident that no other party owns copyright in the material, or you have rights to store the material and, if you are sharing it, that you have the right to do so.

    Please understand that:

    21.1. When we receive your counter-notice, we pass it, including your address and other contact information, to the party who issued the original takedown notice. By submitting your counter-notice you authorise us to do so.

So it gets better. To keep your files after a potentially malicious copyright notice, you have to file a counter-notice. But when you file a counter-notice, Ente gives your address and contact information to the malicious actor who filed takedown notices. WTF so if I file copyright notices for all users’ photos, not only users would need to file counter notices to keep their photos, but Ente would also give me their addresses and contact information!? How convenient!

So don’t confuse Ente for a privacy service provider. It’s just an app, and likely made by a bunch of people with their heart in the right place, but actions (and company) in all the wrong places. I wouldn’t trust them to keep your data safe at all.

. . .

**Comment by vishnukvmd** [comment]
Hey, @DudeDude2, @pluja, one of the founders of ente here. Here's our response to this comment:

1. Yes, our source code is more open than what was specified in our terms. This was a human error, which we fixed as soon as it was pointed out. We do have [lawyers](https://www.inventuslaw.com/).
2. We offer the same level of data protection as any other multi-national company (Apple, Dropbox, Google, Microsoft, ...). In fact more, since your data is e2ee. You can read more about this [here](https://www.reddit.com/r/enteio/comments/slwpd4/our_vision_for_ente/).
3. This is nonsensical. Our terms have clearly stated that for a successful takedown request, the reporter has to submit both the file identifier and the decryption key ([Clause 17.3](https://ente.io/terms/#copyright-infringement-notices)). This means only those you have explicitly shared your files with can submit a takedown request for those files.
4. Again, you can request a takedown for all our users only if you have managed to get hold of every single user's device, and all of their encryption keys.

If you have any follow up questions, I'd be more than happy to address them here :)

I sincerely hope you will re-evaluate your decision to delist ente.
