### ISSUE TITLE
Add Skip Redirect addon

### ISSUE THREAD

**Issue by BardiaB8** [pluja/awesome-privacy#307]
### Skip Redirect
* [Skip Redirect](https://github.com/sblask/webextension-skip-redirect) - some sites, when using a hyperlink, use links that redirect to the original site. this add-on attempts to extract the URL and loading the site right away.
* **License**: <MIT>
* **Why do you think this helps users privacy?**: prevent sites from knowing if the user opened a hyperlink.
* **Under what section should this service be listed?**: browser addons

**Comment by supleed2** [comment]
The GitHub only seems to link to the Firefox version, it also exists on the Chrome web store but you'd need to find it yourself:
https://chrome.google.com/webstore/detail/skip-redirect/jaoafjdoijdconemdmodhbfpianehlon

**Comment by monokrome** [comment]
Its worth noting that there are more mature solutions to this problem (which I think are already included in this repository) and this specific addon feels pretty alpha-quality since it has [some open issues](https://github.com/sblask/webextension-skip-redirect/issues/255) which could directly affect a users privacy in a negative way. I'd suggest that this may not be worth adding in its current state, although it may be something to keep an eye on in the future.
